### ISSUE TITLE
about configure giscus in docsify

### ISSUE THREAD

**Issue by xdd1997** [Steveplays28/nularc#15]
I want to configure giscus in docsify  refer to your website, but I find that your comment system is not open. Is it because you intentionally closed the comment system or it is not well configured?
If it's convenient, can you tell me how to embed the js code from giscus into index.html?

**Comment by Steveplays28** [comment]
Hey, I thought about adding giscus to my docs a while ago but ultimately decided It's not necessary.
So I can't really help with that, sorry!

**Comment by xdd1997** [comment]
Thank you for your reply and best wishes.

**Comment by Steveplays28** [comment]
Thanks, you too! Good luck with giscus
